Repository openid/OpenID4VCI, pull requests merged in 2025-06, with the labels that each got.

#533 Clarify that number of issued credentials is related to number of keys
  openid-4-verifiable-credential-issuance-1_0.md
Labels: editorial, reviews-needed

#543 Add example key_attestations_required, add ISO 18045 ref, specify 'non-empty' arrays
  examples/credential_metadata_sd_jwt_vc.json
  openid-4-verifiable-credential-issuance-1_0.md
Labels: editorial

#517 Remove the option to use `format` from `authorization_details` in the Authorization Request
  examples/authorization_details_sd_jwt_vc.json
  openid-4-verifiable-credential-issuance-1_0.md
Labels: priority

#524 Attempt to clarify intro text about key attestations
  openid-4-verifiable-credential-issuance-1_0.md
Labels: editorial, reviews-needed

#521 Add text requiring that the issuer value in metadata is validated
  openid-4-verifiable-credential-issuance-1_0.md
Labels: reviews-needed

#529 require proof_signing_alg_values_supported to match key proof algorithms and rename ldp_vp to di_vp
  openid-4-verifiable-credential-issuance-1_0.md
Labels: reviews-needed

#495 fix signing alg values supported for ISO mdos in metadata
  examples/credential_metadata_mso_mdoc.json
  openid-4-verifiable-credential-issuance-1_0.md
Labels: discuss, priority

#500 decouple credential metadata
  examples/credential_issuer_metadata_jwt_vc_json.json
  examples/credential_metadata_jwt_vc_json.json
  examples/credential_metadata_ldp_vc.json
  examples/credential_metadata_mso_mdoc.json
  examples/credential_metadata_sd_jwt_vc.json
  openid-4-verifiable-credential-issuance-1_0.md
Labels: reviews-needed

#550 re-adding missing file examples/authorization_details_sd_jwt_vc.json
  examples/authorization_details_sd_jwt_vc.json
Labels: editorial

#489 move proof types to Annex F
  openid-4-verifiable-credential-issuance-1_0.md
Labels: editorial

#520 add option to have signed Credential Issuer metadata, remove `signed_metadata` from Credential Issuer metadata
  openid-4-verifiable-credential-issuance-1_0.md
Labels: priority

#559 Add missing entries to document history
  openid-4-verifiable-credential-issuance-1_0.md
Labels: editorial
